### PR TITLE
Update components with Tally Wallet.

### PR DESCRIPTION
**Pull request by torreyatcitty**
Screen Shot 2022-02-25 at 2 16 36 PM

### CODE REVIEW

**Review by mykelp — APPROVED** [review]
👍  --- Where did the arrows go?

**Comment by torreyatcitty** [comment]
oh yeah, where did the arrows go??? I'll check.

**Comment by torreyatcitty** [comment]
Fixed missing arrows.

**Comment by torreyatcitty** [comment]
Screen Shot 2022-02-25 at 2 40 57 PM

**Pull request merged**
